@startuml erd
!include tables.pu

    contractors ||-d-o{ contract_lines
    contract_lines ||-d-o{ contract_devices
    contract_lines ||-o{ monthly_payment_histories
    base_contract_contents ||-contract_lines
@enduml