@startuml

usecase 機種変更
actor 契約者
actor 非契約者
boundary 機種変更画面
boundary 機種選択画面
boundary 購入方法選択画面
boundary 料金プラン選択画面
boundary 毎月の支払い方法選択画面
boundary 毎月の想定料金と支払い方法を表示する
control 毎月の想定料金算出
control 機種変更コントローラ
control 分割審査
control 丁寧審査
control 信用情報API
entity 契約者情報


control 本人確認書類と入力値の照合
control 契約不可エラー
entity 本人確認書類オブジェクト


契約者 --> 機種変更画面
機種変更画面 -> 機種変更コントローラ
機種変更コントローラ -->本人確認書類と入力値の照合
本人確認書類と入力値の照合 --> 契約不可エラー : 失敗
本人確認書類と入力値の照合 --> 機種選択画面 : 本人確認成功
本人確認書類と入力値の照合--本人確認書類オブジェクト
機種選択画面 --> 購入方法選択画面
購入方法選択画面 --> 分割審査: 分割
購入方法選択画面 --> 料金プラン選択画面: 一括
分割審査 -- 契約者情報
分割審査 --> 料金プラン選択画面 : 分割可能
分割審査 --> 購入方法選択画面 : 分割不可
分割審査 --> 丁寧審査: 10万以上の機種
丁寧審査 --> 契約者情報
契約者情報 -- 信用情報API
丁寧審査 --> 機種選択画面: 丁寧審査不合格(10万未満の機種を選択してもらう)
料金プラン選択画面 --> 毎月の支払い方法選択画面
毎月の支払い方法選択画面 -- 毎月の想定料金算出
毎月の支払い方法選択画面 --> 毎月の想定料金と支払い方法を表示する
@enduml