left to right direction

hide circle
hide method

package 契約者 {
    class 契約者 #F5A9BC{
        姓: String
        名前: String
        生年月日: Date
        現在の契約台数
        支払い履歴
    }
    class 利用者 #F5A9BC {
        姓: String
        名前: String
        生年月日: Date

    }

    契約者 *-- 支払い履歴
}

class 支払い履歴 {



}


package 本人確認 {

    interface 本人確認書類 {
        氏名
        生年月日
        現住所
    }
    note bottom: 実際の現住所 = 記載の現住所\n,氏名,生年月日, 現住所が記載\nで有効期限内

    class 運転免許証 {
        有効期限
    }

    class マイナンバーカード {
        有効期限
    }

    class 健康保険証 {
    }
    note bottom: 支払い方法をクレジットまたは補助書類が必要


    class 住民基本台帳カード {

    }
    note bottom: 支払い方法をクレジットまたはキャッシュカードまたは補助書類が必要



    interface 補助書類 {
        氏名
        生年月日
        現住所
        発効日
    }
    note bottom: 氏名,生年月日, 現住所が記載\nで発効日から3ヶ月以内

    class 住民票 {
        
    }

    class 公共料金領収書 {

    }

    補助書類  <|-- 住民票
    補助書類 <|-- 公共料金領収書
    本人確認書類  <|-- 運転免許証
    本人確認書類 <|-- マイナンバーカード
    本人確認書類  <|-- 健康保険証
    本人確認書類 <|-- 住民基本台帳カード
    契約者 o--> 本人確認書類 : has-many
    利用者 o--> 本人確認書類 : has-many

}

class 購入機種代金 {
    税込金額
    税抜き金額
    税
}

package 購入方法 {

    interface 購入方法

    class 一括 {
        機種代金
    }
    class 分割 {
        分割回数
        機種代金
    }
    note bottom: 機種が１０万未満→与信審査\n機種が１０万以上→丁寧審査

    class 分割審査不合格判定 {
        分割可能フラグ

    }
    note bottom: 三ヶ月分以上の料金の滞納がある\n現在の支払い方法が請求書\n2台分の料金を分割払いで支払っている人

    購入方法  <|-- 一括
    購入方法 <|-- 分割
    分割 ..> 購入機種代金
    分割審査不合格判定 ..> 契約者
}



package 毎月の支払い方法 {
    interface 支払い方法 

    class 請求書
    class 口座振替
    note bottom: 通帳＋印鑑または\nキャッシュカードが必要
    class クレジット
    note bottom: 契約者の名義であること

    支払い方法  <|-- 請求書
    支払い方法 <|-- 口座振替
    支払い方法  <|-- クレジット

}
package 想定毎月の料金算出 {
    class 想定毎月の料金 {
        家族割
        光セット割
        購入方法
        料金プラン
        支払い方法
    }
    note bottom: 家族割の条件はそれぞれの本人確認書類の記載住所が同一またはご家族が確認できる書類がある場合


    想定毎月の料金 *-- 支払い方法
    想定毎月の料金 *-- 購入方法
    想定毎月の料金 *-- 料金プラン
    想定毎月の料金 *-- 割引
}

package 割引 {
    class 家族割 {
        divied_price: 1000
    }
    note bottom: 家族割の条件はそれぞれの本人確認書類の記載住所が同一またはご家族が確認できる書類がある場合

    class 光セット割 {
        divied_price: 1000
    }
}

package 料金プラン {
    interface 料金プラン {
        基本料金
        使えるギガ
        割引
    }

    class メリハリプラン {
        基本料金: 7238円
        家族割
        光セット割
        使えるギガ

    }
    note bottom: 基本料金:7238円\n家族割(3回線以上 100円)\n光セット割(1000円)

    class ミニフィットプラン {
        基本料金: 3278円スタートで1gb毎に1100円増加
        光セット割
        使えるギガ: 3gb
    }
    note bottom: 基本料金: ~1gb 3278円 ~3gb 5478円(1gb毎に1100円増加)\n光セット割(1000円)


    料金プラン <|-- メリハリプラン
    料金プラン <|-- ミニフィットプラン
}



